export default function Head() {
  return (
    <>
      <title>Weather</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        name="description"
        content="An app to follow market trends made by Sethy Laleye and generated by create next app"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
